name: Build
on:
  workflow_call: {}
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [esp32s3, esp32p4]
        idf_version: [v5.4.4, v5.5.3]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { submodules: recursive }
      - name: Build All
        uses: espressif/esp-idf-ci-action@e6f5c74232b1ccd4c97ed641f1e48553853f1fd5 # v1.2.0
        with:
          esp_idf_version: ${{ matrix.idf_version }}
          command: |
            pip install idf-build-apps
            idf-build-apps build --recursive --target ${{ matrix.target }}
