name: Build Documentation
on:
  workflow_call:
    inputs:
      deploy:
        type: boolean
        description: Deploy to GitHub Pages
        default: false
jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@f13be1686235deee0aeb6cdf56640170691dc96b # v1
        with: { version: "1.14.0" }
      - name: Build
        run: cd docs && doxygen
      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Upload Generated Docs
        if: ${{ inputs.deploy }}
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with: { path: docs/output/html }
  deploy-docs:
    name: Deploy Documentation
    needs: build-docs
    if: ${{ inputs.deploy }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
