name: Host Tests
on:
  workflow_call: {}
  workflow_dispatch: {}
jobs:
  host-test:
    name: Host Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with: { submodules: recursive }
      - name: Configure
        working-directory: components/livekit/host_test
        run: cmake -S . -B build
      - name: Build
        working-directory: components/livekit/host_test
        run: cmake --build build
      - name: Test
        working-directory: components/livekit/host_test
        run: ctest --test-dir build --output-on-failure
