name: Release
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  registry-upload:
    name: Registry Upload
    uses: ./.github/workflows/esp_registry.yml
    with: { dry_run: false }
  deploy-docs:
    name: Deploy Documentation
    uses: ./.github/workflows/docs.yml
    with: { deploy: true }